version: '3.7'
services:
  idp:
    build:
      context: .
      args:
        SIMPLESAMLPHP_VERSION: "1.19.8"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http:///saml/callback?org_slug=default
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http:///saml/callback?org_slug=default
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http:///saml/callback?org_slug=default
      SIMPLESAMLPHP_IDP_ADMIN_PASSWORD:
      SIMPLESAMLPHP_IDP_SECRET_SALT:
    ports:
      - "8080:8080"
    volumes:
      - ./authsources.php:/var/www/simplesamlphp/config/authsources.php
